version: '3.7'

services:
  msg-cs-db:
    container_name: msg-cs-db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - msgcs-database-data-volume:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  msgcs-database-data-volume:
